/********************************************************************
* /home/dorfer/kdetsim/src/KDetSimDictUX.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error /home/dorfer/kdetsim/src/KDetSimDictUX.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableKDetSimDictUX();
extern void G__cpp_setup_inheritanceKDetSimDictUX();
extern void G__cpp_setup_typetableKDetSimDictUX();
extern void G__cpp_setup_memvarKDetSimDictUX();
extern void G__cpp_setup_globalKDetSimDictUX();
extern void G__cpp_setup_memfuncKDetSimDictUX();
extern void G__cpp_setup_funcKDetSimDictUX();
extern void G__set_cpp_environmentKDetSimDictUX();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "/home/dorfer/kdetsim/inc/KPad.h"
#include "/home/dorfer/kdetsim/inc/KDetector.h"
#include "/home/dorfer/kdetsim/inc/KField.h"
#include "/home/dorfer/kdetsim/inc/K3D.h"
#include "/home/dorfer/kdetsim/inc/KPixel.h"
#include "/home/dorfer/kdetsim/inc/KGeometry.h"
#include "/home/dorfer/kdetsim/inc/KMaterial.h"
#include "/home/dorfer/kdetsim/inc/KStruct.h"
#include "/home/dorfer/kdetsim/inc/KStrip.h"
#include "/home/dorfer/kdetsim/inc/KMesh.h"
#include "/home/dorfer/kdetsim/inc/KImplant3D.h"
#include "/home/dorfer/kdetsim/inc/KImplant2D.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__KDetSimDictUXLN_TClass;
extern G__linked_taginfo G__KDetSimDictUXLN_TBuffer;
extern G__linked_taginfo G__KDetSimDictUXLN_TMemberInspector;
extern G__linked_taginfo G__KDetSimDictUXLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__KDetSimDictUXLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KDetSimDictUXLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__KDetSimDictUXLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TArrayF;
extern G__linked_taginfo G__KDetSimDictUXLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__KDetSimDictUXLN_TF1;
extern G__linked_taginfo G__KDetSimDictUXLN_TH1D;
extern G__linked_taginfo G__KDetSimDictUXLN_TH1F;
extern G__linked_taginfo G__KDetSimDictUXLN_TRandom;
extern G__linked_taginfo G__KDetSimDictUXLN_TGraph;
extern G__linked_taginfo G__KDetSimDictUXLN_TH3I;
extern G__linked_taginfo G__KDetSimDictUXLN_TH3F;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__KDetSimDictUXLN_TH2F;
extern G__linked_taginfo G__KDetSimDictUXLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TVector3;
extern G__linked_taginfo G__KDetSimDictUXLN_KField;
extern G__linked_taginfo G__KDetSimDictUXLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__KDetSimDictUXLN_TFile;
extern G__linked_taginfo G__KDetSimDictUXLN_TROOT;
extern G__linked_taginfo G__KDetSimDictUXLN_KMaterial;
extern G__linked_taginfo G__KDetSimDictUXLN_KStruct;
extern G__linked_taginfo G__KDetSimDictUXLN_TF3;
extern G__linked_taginfo G__KDetSimDictUXLN_KGeometry;
extern G__linked_taginfo G__KDetSimDictUXLN_KDetector;
extern G__linked_taginfo G__KDetSimDictUXLN_KPad;
extern G__linked_taginfo G__KDetSimDictUXLN_K3D;
extern G__linked_taginfo G__KDetSimDictUXLN_KPixel;
extern G__linked_taginfo G__KDetSimDictUXLN_KStrip;
extern G__linked_taginfo G__KDetSimDictUXLN_KMesh;
extern G__linked_taginfo G__KDetSimDictUXLN_KImplant3D;
extern G__linked_taginfo G__KDetSimDictUXLN_KImplant2D;

/* STUB derived class for protected member access */
